#!/bin/bash

set -euo pipefail

# This script replaces the first line of the commit message with the issue id of the current branch.
# Currently, commit types (second argument, see https://git-scm.com/docs/githooks#_prepare_commit_msg) are not supported.

if [[ $# -eq 1 ]]; then
    issue_id=$(git symbolic-ref --short HEAD 2>/dev/null | grep -Eo '^[a-z]+[/-]I[A-Z]+-[0-9]+-' | awk -F '[/-]' '{print $2"-"$3}')
    if [[ -n "${issue_id}" ]]; then
        # in-place substitution of first line of commit message file
        sed -i '' "1s/^.*$/${issue_id} /" "$1"
    fi
fi