#!/bin/bash
#: exec_target = cli
#
## Runs phpcs
## Usage: fin phpcs [params to passthrough]

set -eo pipefail

CACHE_FILE=${PROJECT_ROOT}/var/cache/dev/phpcs.cache
mkdir -p $(dirname "${CACHE_FILE}")
${PROJECT_ROOT}/vendor/bin/phpcs --cache="${CACHE_FILE}" --basepath="${PROJECT_ROOT}" "${@}"
